[package]
name = "clicker-app"
version = "0.1.0"
edition = "2021"
rust-version = "1.96"

[lib]
name = "clicker_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clicker-core = { path = "../../crates/clicker-core" }
tauri-plugin-global-shortcut = "2.3.2"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
